### ISSUE TITLE
View Archived Properties

### ISSUE THREAD

**Issue by jackdaug** [codeyoungstown/yndc-board-up#18]
We need a way to view archived properties so that once work is completed, we can archive them, but still review them if we need to look back on what has been completed.

**Comment by nicholasserra** [comment]
This fix is in and deployed. Toggling between archived and not archived is a bit slow since there's no pagination yet. So give it a second between toggling.

**Comment by jackdaug** [comment]
Thanks nick.

On Tuesday, May 19, 2015, Nicholas Serra <notifications@github.com> wrote:

> This fix is in and deployed. Toggling between archived and not archived is
> a bit slow since there's no pagination yet. So give it a second between
> toggling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeyoungstown/yndc-board-up/issues/18#issuecomment-103346899>
> .
>


-- 
Jack N. Daugherty III
jndaugherty3@gmail.com
