### ISSUE TITLE
Logout Button

### ISSUE THREAD

**Issue by jackdaug** [codeyoungstown/yndc-board-up#19]
There is currently not a button that enables us to log out of our accounts. We sometimes experience issues logging back in on the same computer as a result.

**Comment by jackdaug** [comment]
THANK YOU.

On Tue, May 12, 2015 at 11:34 PM, Nicholas Serra <notifications@github.com>
wrote:

> Closed #19 <https://github.com/codeyoungstown/yndc-board-up/issues/19>
> via cafdd13
> <https://github.com/codeyoungstown/yndc-board-up/commit/cafdd138a0bc0b0eee8c3554c066ff577a3a7f37>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeyoungstown/yndc-board-up/issues/19#event-303457028>
> .
>



-- 
Jack N. Daugherty III
jndaugherty3@gmail.com

**Comment by nicholasserra** [comment]
:D This is deployed, also.
