### ISSUE TITLE
Batch printing with pagination.

### ISSUE THREAD

**Issue by jackdaug** [codeyoungstown/yndc-board-up#26]
Currently the app does not allow you to select properties to batch print across multiple pages. This has created a problem in compiling work plan documents that must span more than one page.

**Comment by nicholasserra** [comment]
Should be able to fix this by wiring in an "amount per page" selector 

via Hiptop

**Comment by nicholasserra** [comment]
Code done for this. Need to make a couple tweaks then it will be deployed. Prob within the hour.

**Comment by jackdaug** [comment]
Awesome.

On Fri, Jun 19, 2015 at 3:29 PM, Nicholas Serra <notifications@github.com>
wrote:

> Code done for this. Need to make a couple tweaks then it will be deployed.
> Prob within the hour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeyoungstown/yndc-board-up/issues/26#issuecomment-113614732>
> .
>



-- 
Jack N. Daugherty III
jndaugherty3@gmail.com

**Comment by nicholasserra** [comment]
![screen shot 2015-06-19 at 3 40 12 pm](https://cloud.githubusercontent.com/assets/512288/8261560/7b6084e0-1699-11e5-8fa7-60e0082504bf.png)
