### ISSUE TITLE
55 57 returns error

### ISSUE THREAD

**Issue by gtaylorYNDC** [codeyoungstown/yndc-board-up#33]
There is a property that was created quite a while ago that is name 55 57. There are two instances of this property. Each time I try to open either of these entries it crashes to an error page.
```
MultipleObjectsReturned at /property/55-57
get() returned more than one House -- it returned 2!
Request Method:	GET
Request URL:	http://yndc.herokuapp.com/property/55-57
Django Version:	1.7
Exception Type:	MultipleObjectsReturned
Exception Value:	
get() returned more than one House -- it returned 2!
Exception Location:	/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py in get, line 361
Python Executable:	/app/.heroku/python/bin/python
Python Version:	2.7.8
Python Path:	
['/app/yndc/apps',
 '/app',
 '/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg']
Server time:	Fri, 25 Nov 2016 10:43:11 -0500
```
I get the same error if I attempt to delete one as well. I am assuming that it is the same entry that is duplicated and one can be deleted but I am not sure. Is there anything that can be done about this issue?

[http://yndc.herokuapp.com/property/55-57](url)

**Comment by nicholasserra** [comment]
Yeah somehow there were duplicates of this property. I changed the slug of one of them so you can see them. They are now at:

http://yndc.herokuapp.com/property/55-57
http://yndc.herokuapp.com/property/55-57-2

So pick the one that's correct and delete the other :)

**Comment by gtaylorYNDC** [comment]
Thank you so much.
